name: Ping Squidly API
on:
  schedule:
    - cron: "*/15 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: ⚙️ Checkout repo
        uses: actions/checkout@v4
      - name: 🔄 Ping beta api
        shell: bash
        run: |
          curl --location '${{ secrets.SQUIDLY_BETA_PING_ENDPOINT }}' \
               --header 'x-monitoring-secret: ${{ secrets.SQUIDLY_BETA_SECRET_HEADER }}'
